// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NhaMayThep.Infrastructure.Persistence;

#nullable disable

namespace NhaMayThep.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240113015719_v1")]
    partial class v1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NhaMapThep.Domain.Entities.CanCuocCongDanEntity", b =>
                {
                    b.Property<string>("CanCuocCongDan")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("DanToc")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("DiaChiThuongTru")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("GioiTinh")
                        .HasColumnType("bit");

                    b.Property<string>("HoVaTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayCap")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayCapNhatCuoi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhatID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTaoID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoiCap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QueQuan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuocTich")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TonGiao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CanCuocCongDan");

                    b.ToTable("ThongTinCanCuocCongDan");
                });

            modelBuilder.Entity("NhaMapThep.Domain.Entities.ConfigTable.LoaiHopDongEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TenHopDong");

                    b.HasKey("ID")
                        .HasName("MaHopDong");

                    b.ToTable("LoaiHopDong");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "HopDongThuViec"
                        },
                        new
                        {
                            ID = 2,
                            Name = "HopDongCoThoiHan"
                        },
                        new
                        {
                            ID = 3,
                            Name = "HopDongKhongThoiHan"
                        });
                });

            modelBuilder.Entity("NhaMapThep.Domain.Entities.ConfigTable.ThongTinChucDanhEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TenChucDanh");

                    b.HasKey("ID")
                        .HasName("MaChucDanh");

                    b.ToTable("ThongTinChucDanhEntity");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "GiamDoc"
                        },
                        new
                        {
                            ID = 2,
                            Name = "PhoGiamDoc"
                        },
                        new
                        {
                            ID = 3,
                            Name = "TruongPhong"
                        },
                        new
                        {
                            ID = 4,
                            Name = "PhoPhong"
                        },
                        new
                        {
                            ID = 5,
                            Name = "NhanVien"
                        });
                });

            modelBuilder.Entity("NhaMapThep.Domain.Entities.ConfigTable.ThongTinChucVuEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TenChucVu");

                    b.HasKey("ID")
                        .HasName("MaChucVu");

                    b.ToTable("ThongTinChucVu");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            ID = 2,
                            Name = "Truong Phong Nhan Su"
                        },
                        new
                        {
                            ID = 3,
                            Name = "Quan Li"
                        },
                        new
                        {
                            ID = 4,
                            Name = "Nhan Vien"
                        });
                });

            modelBuilder.Entity("NhaMapThep.Domain.Entities.ConfigTable.ThongTinGiamTruEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TenMaGiamTru");

                    b.Property<decimal>("SoTienGiamTru")
                        .HasColumnType("decimal(18, 4)");

                    b.HasKey("ID")
                        .HasName("MaGiamTru");

                    b.ToTable("ThongTinGiamTru");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "GiamTruBanThan",
                            SoTienGiamTru = 11000000m
                        },
                        new
                        {
                            ID = 2,
                            Name = "GiamTruNguoiPhuThuoc",
                            SoTienGiamTru = 4400000m
                        });
                });

            modelBuilder.Entity("NhaMapThep.Domain.Entities.ConfigTable.TinhTrangLamViecEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TenMaTinhTrangLamViec");

                    b.HasKey("ID")
                        .HasName("MaTinhTrangLamViecID");

                    b.ToTable("ThongTinTinhTrangLamViec");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "DangLamViec"
                        },
                        new
                        {
                            ID = 2,
                            Name = "DaNghiViec"
                        },
                        new
                        {
                            ID = 3,
                            Name = "DangThuViec"
                        },
                        new
                        {
                            ID = 4,
                            Name = "DangNghiPhep"
                        });
                });

            modelBuilder.Entity("NhaMapThep.Domain.Entities.NhanVienEntity", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CanCuocCongDan")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<int>("ChucVuID")
                        .HasColumnType("int");

                    b.Property<string>("DiaChiLienLac")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoVaTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaSoThue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayCapNhatCuoi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayVaoCongTy")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhatID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTaoID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDienThoaiLienLac")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<int?>("SoNguoiPhuThuoc")
                        .HasColumnType("int");

                    b.Property<string>("SoTaiKhoan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenNganHang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TinhTrangLamViecID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ChucVuID");

                    b.HasIndex("TinhTrangLamViecID");

                    b.ToTable("NhanVien");
                });

            modelBuilder.Entity("NhaMapThep.Domain.Entities.ThongTinGiamTruGiaCanhEntity", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CanCuocCongDan")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("DiaChiLienLac")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaGiamTruID")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayCapNhatCuoi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayXacNhanPhuThuoc")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhatID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTaoID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NhanVienID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("QuanHeVoiNhanVien")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ID");

                    b.HasIndex("CanCuocCongDan")
                        .IsUnique();

                    b.HasIndex("MaGiamTruID");

                    b.HasIndex("NhanVienID");

                    b.ToTable("ThongTinGiamTruGiaCanh");
                });

            modelBuilder.Entity("NhaMapThep.Domain.Entities.CanCuocCongDanEntity", b =>
                {
                    b.OwnsMany("NhaMapThep.Domain.Entities.Mapping.NhanVienMapThongTinCanCuocCongDan", "NhanVienMapThongTinCanCuocCongDan", b1 =>
                        {
                            b1.Property<int>("ID")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("ID"));

                            b1.Property<string>("CanCuocCongDan")
                                .IsRequired()
                                .HasColumnType("nvarchar(12)");

                            b1.Property<string>("MaSoNhanVien")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("ID");

                            b1.HasIndex("CanCuocCongDan");

                            b1.ToTable("ThongTinCanCuocCongDan_NhanVienMapThongTinCanCuocCongDan");

                            b1.WithOwner()
                                .HasForeignKey("CanCuocCongDan");
                        });

                    b.Navigation("NhanVienMapThongTinCanCuocCongDan");
                });

            modelBuilder.Entity("NhaMapThep.Domain.Entities.NhanVienEntity", b =>
                {
                    b.HasOne("NhaMapThep.Domain.Entities.ConfigTable.ThongTinChucVuEntity", "ChucVu")
                        .WithMany()
                        .HasForeignKey("ChucVuID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NhaMapThep.Domain.Entities.ConfigTable.TinhTrangLamViecEntity", "TinhTrangLamViec")
                        .WithMany()
                        .HasForeignKey("TinhTrangLamViecID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("NhaMapThep.Domain.Entities.Mapping.NhanVienMapThongTinCanCuocCongDan", "NhanVienMapThongTinCanCuocCongDans", b1 =>
                        {
                            b1.Property<int>("ID")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("ID"));

                            b1.Property<string>("CanCuocCongDan")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("MaSoNhanVien")
                                .IsRequired()
                                .HasColumnType("nvarchar(450)");

                            b1.HasKey("ID");

                            b1.HasIndex("MaSoNhanVien");

                            b1.ToTable("NhanVien_NhanVienMapThongTinCanCuocCongDans");

                            b1.WithOwner()
                                .HasForeignKey("MaSoNhanVien");
                        });

                    b.Navigation("ChucVu");

                    b.Navigation("NhanVienMapThongTinCanCuocCongDans");

                    b.Navigation("TinhTrangLamViec");
                });

            modelBuilder.Entity("NhaMapThep.Domain.Entities.ThongTinGiamTruGiaCanhEntity", b =>
                {
                    b.HasOne("NhaMapThep.Domain.Entities.CanCuocCongDanEntity", "SoCanCuoc")
                        .WithOne("ThongTinGiamTruGiaCanh")
                        .HasForeignKey("NhaMapThep.Domain.Entities.ThongTinGiamTruGiaCanhEntity", "CanCuocCongDan")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NhaMapThep.Domain.Entities.ConfigTable.ThongTinGiamTruEntity", "ThongTinGiamTru")
                        .WithMany()
                        .HasForeignKey("MaGiamTruID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NhaMapThep.Domain.Entities.NhanVienEntity", "NhanVien")
                        .WithMany()
                        .HasForeignKey("NhanVienID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");

                    b.Navigation("SoCanCuoc");

                    b.Navigation("ThongTinGiamTru");
                });

            modelBuilder.Entity("NhaMapThep.Domain.Entities.CanCuocCongDanEntity", b =>
                {
                    b.Navigation("ThongTinGiamTruGiaCanh");
                });
#pragma warning restore 612, 618
        }
    }
}
