// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NhaMayThep.Infrastructure.Persistence;

#nullable disable

namespace NhaMayThep.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240321234617_v")]
    partial class v
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CanCuocCongDanEntityNhanVienEntity", b =>
                {
                    b.Property<string>("NhanVienID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NhanVienID1")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("NhanVienID", "NhanVienID1");

                    b.HasIndex("NhanVienID1");

                    b.ToTable("CanCuocCongDanEntityNhanVienEntity");
                });

            modelBuilder.Entity("NhaMapThep.Domain.Entities.BaoHiemNhanVienEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("BaoHiem")
                        .HasColumnType("int");

                    b.Property<string>("MaSoNhanVien")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayXoa")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhatID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTaoID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiXoaID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID")
                        .HasName("MaBHNV");

                    b.HasIndex("MaSoNhanVien");

                    b.ToTable("BaoHiemNhanVien");
                });

            modelBuilder.Entity("NhaMapThep.Domain.Entities.CanCuocCongDanEntity", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CanCuocCongDan")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("DanToc")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("DiaChiThuongTru")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("GioiTinh")
                        .HasColumnType("bit");

                    b.Property<string>("HoVaTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayCap")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayCapNhatCuoi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayXoa")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhatID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTaoID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiXoaID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NhanVienID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoiCap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QueQuan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuocTich")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TonGiao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("CanCuocCongDan");
                });

            modelBuilder.Entity("NhaMapThep.Domain.Entities.ChiTietBaoHiemEntity", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("LoaiBaoHiem")
                        .HasColumnType("int");

                    b.Property<string>("MaSoNhanVien")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("NgayCapNhatCuoi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayHieuLuc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayXoa")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhatID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTaoID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiXoaID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoiCap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID")
                        .HasName("MaSo");

                    b.HasIndex("LoaiBaoHiem");

                    b.HasIndex("MaSoNhanVien");

                    b.ToTable("ChiTietBaoHiem");
                });

            modelBuilder.Entity("NhaMapThep.Domain.Entities.ChiTietNgayNghiPhepEntity", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("LoaiNghiPhepID")
                        .HasColumnType("int");

                    b.Property<string>("MaSoNhanVien")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("NamHieuLuc")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayCapNhatCuoi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayXoa")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhatID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTaoID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiXoaID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("SoGioConLai")
                        .HasColumnType("float");

                    b.Property<double>("SoGioDaNghiPhep")
                        .HasColumnType("float");

                    b.Property<double>("TongSoGio")
                        .HasColumnType("float");

                    b.HasKey("ID");

                    b.HasIndex("LoaiNghiPhepID");

                    b.HasIndex("MaSoNhanVien");

                    b.ToTable("ChiTietNgayNghiPhep");
                });

            modelBuilder.Entity("NhaMapThep.Domain.Entities.ChinhSachNhanSuEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("MucDo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LoaiHinhThuc");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayHieuLuc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayXoa")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhatID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTaoID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiXoaID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID")
                        .HasName("ChinhSachNhanSuID");

                    b.ToTable("ChinhSachNhanSu");
                });

            modelBuilder.Entity("NhaMapThep.Domain.Entities.ConfigTable.BaoHiemEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("BaoHiem")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TenLoaiBaoHiem")
                        .HasColumnOrder(2);

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayXoa")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhatID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTaoID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiXoaID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PhanTramKhauTru")
                        .HasColumnType("float")
                        .HasColumnOrder(6);

                    b.HasKey("ID")
                        .HasName("MaBaoHiem");

                    b.HasIndex("BaoHiem");

                    b.ToTable("BaoHiem");
                });

            modelBuilder.Entity("NhaMapThep.Domain.Entities.ConfigTable.CapBacLuongEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<float>("HeSoLuong")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayXoa")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhatID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTaoID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiXoaID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrinhDo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("CapBacLuong");
                });

            modelBuilder.Entity("NhaMapThep.Domain.Entities.ConfigTable.DonViCongTacEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayXoa")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhatID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTaoID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiXoaID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("DonViCongTac");
                });

            modelBuilder.Entity("NhaMapThep.Domain.Entities.ConfigTable.LoaiCongTacEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TenLoaiCongTac");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayXoa")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhatID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTaoID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiXoaID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID")
                        .HasName("MaLoaiCongTac");

                    b.ToTable("LoaiCongTac");
                });

            modelBuilder.Entity("NhaMapThep.Domain.Entities.ConfigTable.LoaiHoaDonEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TenLoaiHoaDon");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayXoa")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhatID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTaoID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiXoaID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID")
                        .HasName("MaLoaiHoaDon");

                    b.ToTable("LoaiHoaDon");
                });

            modelBuilder.Entity("NhaMapThep.Domain.Entities.ConfigTable.LoaiHopDongEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TenHopDong");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayXoa")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhatID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTaoID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiXoaID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID")
                        .HasName("MaHopDong");

                    b.ToTable("LoaiHopDong");
                });

            modelBuilder.Entity("NhaMapThep.Domain.Entities.ConfigTable.LoaiNghiPhepEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TenLoaiNghiPhep");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayXoa")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhatID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTaoID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiXoaID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID")
                        .HasName("MaLoaiNghiPhep");

                    b.ToTable("LoaiNghiPhep");
                });

            modelBuilder.Entity("NhaMapThep.Domain.Entities.ConfigTable.MaDangKiCaLamEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TenMaDangKi");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayXoa")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhatID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTaoID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiXoaID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ThoiGianCaLamBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ThoiGianCaLamKetThuc")
                        .HasColumnType("datetime2");

                    b.HasKey("ID")
                        .HasName("MaDangKi");

                    b.ToTable("MaDangKiCaLam");
                });

            modelBuilder.Entity("NhaMapThep.Domain.Entities.ConfigTable.PhongBanEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TenPhongBan");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayXoa")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhatID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTaoID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiXoaID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID")
                        .HasName("MaPhongBan");

                    b.ToTable("PhongBan");
                });

            modelBuilder.Entity("NhaMapThep.Domain.Entities.ConfigTable.PhuCapEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<double>("KhoanPhuCap")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TenPhuCap");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayXoa")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhatID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTaoID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiXoaID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PhuCap")
                        .HasColumnType("int");

                    b.HasKey("ID")
                        .HasName("MaPhuCap");

                    b.HasIndex("PhuCap");

                    b.ToTable("PhuCap");
                });

            modelBuilder.Entity("NhaMapThep.Domain.Entities.ConfigTable.ThongTinCapDangVienEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TenCapDangVien");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayXoa")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhatID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTaoID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiXoaID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID")
                        .HasName("MaCapDangVien");

                    b.ToTable("ThongTinCapDangVien");
                });

            modelBuilder.Entity("NhaMapThep.Domain.Entities.ConfigTable.ThongTinChucDanhEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TenChucDanh");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayXoa")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhatID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTaoID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiXoaID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID")
                        .HasName("MaChucDanh");

                    b.ToTable("ThongTinChucDanh");
                });

            modelBuilder.Entity("NhaMapThep.Domain.Entities.ConfigTable.ThongTinChucVuDangEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TenChucVuDang");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayXoa")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhatID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTaoID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiXoaID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID")
                        .HasName("MaChucVuDang");

                    b.ToTable("ThongTinChucVuDang");
                });

            modelBuilder.Entity("NhaMapThep.Domain.Entities.ConfigTable.ThongTinChucVuEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TenChucVu");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayXoa")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhatID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTaoID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiXoaID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID")
                        .HasName("MaChucVu");

                    b.ToTable("ThongTinChucVu");
                });

            modelBuilder.Entity("NhaMapThep.Domain.Entities.ConfigTable.ThongTinGiamTruEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TenMaGiamTru");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayXoa")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhatID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTaoID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiXoaID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SoTienGiamTru")
                        .HasColumnType("decimal(18, 4)");

                    b.HasKey("ID")
                        .HasName("MaGiamTru");

                    b.ToTable("ThongTinGiamTru");
                });

            modelBuilder.Entity("NhaMapThep.Domain.Entities.ConfigTable.ThongTinPhuCapEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayXoa")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhatID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTaoID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiXoaID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PhanTramPhuCap")
                        .HasColumnType("decimal(18, 4)");

                    b.HasKey("ID");

                    b.ToTable("ThongTinPhuCap");
                });

            modelBuilder.Entity("NhaMapThep.Domain.Entities.ConfigTable.ThongTinQuaTrinhNhanSuEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TenMaQuaTrinhNhanSu");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayXoa")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhatID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTaoID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiXoaID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID")
                        .HasName("MaQuaTrinhNhanSu");

                    b.ToTable("ThongTinQuaTrinhNhanSu");
                });

            modelBuilder.Entity("NhaMapThep.Domain.Entities.ConfigTable.ThongTinTrinhDoChinhTriEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TenTrinhDoChinhTri");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayXoa")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhatID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTaoID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiXoaID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID")
                        .HasName("MaTrinhDoChinhTri");

                    b.ToTable("ThongTinTrinhDoChinhTri");
                });

            modelBuilder.Entity("NhaMapThep.Domain.Entities.ConfigTable.ThueSuatEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("BacThue")
                        .HasColumnType("int");

                    b.Property<decimal>("CuoiThuNhapTinhThueTrenNam")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("CuoiThuNhapTinhThueTrenThang")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("DauThuNhapTinhThueTrenNam")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("DauThuNhapTinhThueTrenThang")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayXoa")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhatID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTaoID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiXoaID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PhanTramThueSuat")
                        .HasColumnType("decimal(18, 4)");

                    b.HasKey("ID")
                        .HasName("MaThueSuat");

                    b.ToTable("ThueSuat");
                });

            modelBuilder.Entity("NhaMapThep.Domain.Entities.ConfigTable.TinhTrangLamViecEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TenMaTinhTrangLamViec");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayXoa")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhatID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTaoID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiXoaID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID")
                        .HasName("MaTinhTrangLamViecID");

                    b.ToTable("ThongTinTinhTrangLamViec");
                });

            modelBuilder.Entity("NhaMapThep.Domain.Entities.ConfigTable.TrangThaiDangKiCaLamViecEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TenTrangThai");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayXoa")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhatID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTaoID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiXoaID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID")
                        .HasName("MaTrangThai");

                    b.ToTable("TrangThaiDangKiCaLamViec");
                });

            modelBuilder.Entity("NhaMapThep.Domain.Entities.ConfigTable.TrinhDoHocVanEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TenTrinhDo");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayXoa")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhatID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTaoID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiXoaID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID")
                        .HasName("MaTrinhDoHocVan");

                    b.ToTable("TrinhDoHocVan");
                });

            modelBuilder.Entity("NhaMapThep.Domain.Entities.HoaDonCongTacNhanVienEntity", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DuongDanFile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LichSuCongTacID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("LoaiHoaDonID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayCapNhatCuoi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayXoa")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhatID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTaoID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiXoaID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("LichSuCongTacID");

                    b.HasIndex("LoaiHoaDonID");

                    b.ToTable("HoaDonCongTacNhanVien");
                });

            modelBuilder.Entity("NhaMapThep.Domain.Entities.HopDongEntity", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BoPhanLamViec")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ChucDanhID")
                        .HasColumnType("int");

                    b.Property<int>("ChucVuID")
                        .HasColumnType("int");

                    b.Property<string>("DiaDiemLamViec")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HeSoLuongID")
                        .HasColumnType("int");

                    b.Property<int>("LoaiHopDongID")
                        .HasColumnType("int");

                    b.Property<decimal>("LuongCoBan")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime?>("NgayCapNhatCuoi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKy")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayXoa")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhatID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTaoID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiXoaID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NhanVienID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PhuCapID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ThoiHanHopDong")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ChucDanhID");

                    b.HasIndex("ChucVuID");

                    b.HasIndex("HeSoLuongID");

                    b.HasIndex("LoaiHopDongID");

                    b.HasIndex("NhanVienID");

                    b.ToTable("HopDong");
                });

            modelBuilder.Entity("NhaMapThep.Domain.Entities.LichSuCongTacNhanVienEntity", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("LoaiCongTacID")
                        .HasColumnType("int");

                    b.Property<string>("LyDo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaSoNhanVien")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayCapNhatCuoi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayXoa")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhatID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTaoID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiXoaID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoiCongTac")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("LoaiCongTacID");

                    b.HasIndex("MaSoNhanVien");

                    b.ToTable("LichSuCongTacNhanVien");
                });

            modelBuilder.Entity("NhaMapThep.Domain.Entities.LichSuNghiPhepNhanVienEntity", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("LoaiNghiPhepID")
                        .HasColumnType("int");

                    b.Property<string>("LyDo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaSoNhanVien")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayCapNhatCuoi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayXoa")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhatID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiDuyet")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NguoiTaoID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiXoaID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("LoaiNghiPhepID");

                    b.HasIndex("MaSoNhanVien");

                    b.HasIndex("NguoiDuyet");

                    b.ToTable("LichSuNghiPhepNhanVien");
                });

            modelBuilder.Entity("NhaMapThep.Domain.Entities.LuongThoiGianEntity", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("LuongGio")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("LuongNam")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("LuongNgay")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("LuongThang")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("LuongTuan")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<int>("MaLuongThoiGian")
                        .HasColumnType("int");

                    b.Property<string>("MaSoNhanVien")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgayApDung")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayApDungLuongThoiGian");

                    b.Property<DateTime?>("NgayCapNhatCuoi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayXoa")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhatID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTaoID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiXoaID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("MaSoNhanVien");

                    b.ToTable("LuongThoiGian");
                });

            modelBuilder.Entity("NhaMapThep.Domain.Entities.MucSanPhamEntity", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("LuongMucSanPham")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("MucSanPhamToiDa")
                        .HasColumnType("int");

                    b.Property<int>("MucSanPhamToiThieu")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayCapNhatCuoi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayXoa")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhatID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTaoID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiXoaID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID")
                        .HasName("MaMucSP");

                    b.ToTable("MucSanPham");
                });

            modelBuilder.Entity("NhaMapThep.Domain.Entities.NhanVienEntity", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ChucVuID")
                        .HasColumnType("int");

                    b.Property<bool>("DaCoHopDong")
                        .HasColumnType("bit");

                    b.Property<string>("DiaChiLienLac")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("HoVaTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaSoThue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayCapNhatCuoi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayVaoCongTy")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayXoa")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhatID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTaoID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiXoaID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDienThoaiLienLac")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<int?>("SoNguoiPhuThuoc")
                        .HasColumnType("int");

                    b.Property<string>("SoTaiKhoan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenNganHang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TinhTrangLamViecID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ChucVuID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("TinhTrangLamViecID");

                    b.ToTable("NhanVien");
                });

            modelBuilder.Entity("NhaMapThep.Domain.Entities.PhuCapNhanVienEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("MaSoNhanVien")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayXoa")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhatID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTaoID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiXoaID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PhuCap")
                        .HasColumnType("int");

                    b.HasKey("ID")
                        .HasName("MaPCNV");

                    b.HasIndex("MaSoNhanVien");

                    b.ToTable("PhuCapNhanVien");
                });

            modelBuilder.Entity("NhaMapThep.Domain.Entities.QuaTrinhNhanSuEntity", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ChucDanhID")
                        .HasColumnType("int");

                    b.Property<int>("ChucVuID")
                        .HasColumnType("int");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LoaiQuaTrinhID")
                        .HasColumnType("int");

                    b.Property<string>("MaSoNhanVien")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayCapNhatCuoi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayXoa")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhatID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTaoID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiXoaID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PhongBanID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ChucDanhID");

                    b.HasIndex("ChucVuID");

                    b.HasIndex("LoaiQuaTrinhID");

                    b.HasIndex("MaSoNhanVien");

                    b.HasIndex("PhongBanID");

                    b.ToTable("QuaTrinhNhanSu");
                });

            modelBuilder.Entity("NhaMapThep.Domain.Entities.ThongTinCongTyEntity", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DienThoai")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("DonViQuanLi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoaiHinhDoanhNghiep")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaDoanhNghiep")
                        .HasColumnType("int");

                    b.Property<int>("MaSoThue")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayCapNhatCuoi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayHoatDong")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayXoa")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhatID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiDaiDien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTaoID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiXoaID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoLuongNhanVien")
                        .HasColumnType("int");

                    b.Property<string>("TenQuocTe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenVietTat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TinhTrang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("ThongTinCongTy");
                });

            modelBuilder.Entity("NhaMapThep.Domain.Entities.ThongTinDangVienEntity", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CapDangVien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChucVuDang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DonViCongTacID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayCapNhatCuoi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayVaoDang")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayXoa")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhatID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTaoID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiXoaID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NhanVienID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TrinhDoChinhTri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("DonViCongTacID");

                    b.HasIndex("NhanVienID");

                    b.ToTable("ThongTinDangVien");
                });

            modelBuilder.Entity("NhaMapThep.Domain.Entities.ThongTinDaoTaoEntity", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ChuyenNganh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaTrinhDoHocVanID")
                        .HasColumnType("int");

                    b.Property<DateTime>("NamTotNghiep")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayCapNhatCuoi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayXoa")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhatID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTaoID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiXoaID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NhanVienID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenTruong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrinhDoVanHoa")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("MaTrinhDoHocVanID");

                    b.HasIndex("NhanVienID");

                    b.ToTable("ThongTinDaoTao");
                });

            modelBuilder.Entity("NhaMapThep.Domain.Entities.ThongTinGiamTruGiaCanhEntity", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CanCuocCongDan")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("DiaChiLienLac")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaGiamTruID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayCapNhatCuoi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayXacNhanPhuThuoc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayXoa")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhatID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTaoID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiXoaID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NhanVienID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("QuanHeVoiNhanVien")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ID");

                    b.HasIndex("MaGiamTruID");

                    b.HasIndex("NhanVienID");

                    b.ToTable("ThongTinGiamTruGiaCanh");
                });

            modelBuilder.Entity("NhaMapThep.Domain.Entities.ThongTinLuongNhanVienEntity", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Loai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("LuongCu")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("LuongMoi")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("MaSoHopDong")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaSoNhanVien")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("NgayCapNhatCuoi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayHieuLuc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayXoa")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhatID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTaoID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiXoaID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NhanVienEntityID")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex("MaSoHopDong");

                    b.HasIndex("MaSoNhanVien");

                    b.HasIndex("NhanVienEntityID");

                    b.ToTable("ThongTinLuongNhanVien");
                });

            modelBuilder.Entity("NhaMayThep.Infrastructure.Persistence.ThongTinCongDoanEntity", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("NgayCapNhatCuoi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayGiaNhap")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayXoa")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhatID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTaoID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiXoaID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NhanVienID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("ThuKiCongDoan")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.HasIndex("NhanVienID");

                    b.ToTable("ThongTinCongDoan");
                });

            modelBuilder.Entity("CanCuocCongDanEntityNhanVienEntity", b =>
                {
                    b.HasOne("NhaMapThep.Domain.Entities.CanCuocCongDanEntity", null)
                        .WithMany()
                        .HasForeignKey("NhanVienID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NhaMapThep.Domain.Entities.NhanVienEntity", null)
                        .WithMany()
                        .HasForeignKey("NhanVienID1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NhaMapThep.Domain.Entities.BaoHiemNhanVienEntity", b =>
                {
                    b.HasOne("NhaMapThep.Domain.Entities.NhanVienEntity", "NhanVien")
                        .WithMany()
                        .HasForeignKey("MaSoNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("NhaMapThep.Domain.Entities.ChiTietBaoHiemEntity", b =>
                {
                    b.HasOne("NhaMapThep.Domain.Entities.ConfigTable.BaoHiemEntity", "BaoHiem")
                        .WithMany()
                        .HasForeignKey("LoaiBaoHiem")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NhaMapThep.Domain.Entities.NhanVienEntity", "NhanVien")
                        .WithMany()
                        .HasForeignKey("MaSoNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaoHiem");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("NhaMapThep.Domain.Entities.ChiTietNgayNghiPhepEntity", b =>
                {
                    b.HasOne("NhaMapThep.Domain.Entities.ConfigTable.LoaiNghiPhepEntity", "LoaiNghiPhep")
                        .WithMany()
                        .HasForeignKey("LoaiNghiPhepID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NhaMapThep.Domain.Entities.NhanVienEntity", "NhanVien")
                        .WithMany()
                        .HasForeignKey("MaSoNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiNghiPhep");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("NhaMapThep.Domain.Entities.ConfigTable.BaoHiemEntity", b =>
                {
                    b.HasOne("NhaMapThep.Domain.Entities.BaoHiemNhanVienEntity", null)
                        .WithMany("BaoHiems")
                        .HasForeignKey("BaoHiem");
                });

            modelBuilder.Entity("NhaMapThep.Domain.Entities.ConfigTable.PhuCapEntity", b =>
                {
                    b.HasOne("NhaMapThep.Domain.Entities.PhuCapNhanVienEntity", null)
                        .WithMany("PhuCaps")
                        .HasForeignKey("PhuCap");
                });

            modelBuilder.Entity("NhaMapThep.Domain.Entities.HoaDonCongTacNhanVienEntity", b =>
                {
                    b.HasOne("NhaMapThep.Domain.Entities.LichSuCongTacNhanVienEntity", "LichSuCongTacNhanVien")
                        .WithMany()
                        .HasForeignKey("LichSuCongTacID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NhaMapThep.Domain.Entities.ConfigTable.LoaiHoaDonEntity", "LoaiHoaDon")
                        .WithMany()
                        .HasForeignKey("LoaiHoaDonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LichSuCongTacNhanVien");

                    b.Navigation("LoaiHoaDon");
                });

            modelBuilder.Entity("NhaMapThep.Domain.Entities.HopDongEntity", b =>
                {
                    b.HasOne("NhaMapThep.Domain.Entities.ConfigTable.ThongTinChucDanhEntity", "ChucDanh")
                        .WithMany()
                        .HasForeignKey("ChucDanhID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NhaMapThep.Domain.Entities.ConfigTable.ThongTinChucVuEntity", "ChucVu")
                        .WithMany()
                        .HasForeignKey("ChucVuID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NhaMapThep.Domain.Entities.ConfigTable.CapBacLuongEntity", "CapBacLuong")
                        .WithMany()
                        .HasForeignKey("HeSoLuongID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NhaMapThep.Domain.Entities.ConfigTable.LoaiHopDongEntity", "LoaiHopDong")
                        .WithMany()
                        .HasForeignKey("LoaiHopDongID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NhaMapThep.Domain.Entities.NhanVienEntity", "NhanVien")
                        .WithMany("HopDongs")
                        .HasForeignKey("NhanVienID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CapBacLuong");

                    b.Navigation("ChucDanh");

                    b.Navigation("ChucVu");

                    b.Navigation("LoaiHopDong");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("NhaMapThep.Domain.Entities.LichSuCongTacNhanVienEntity", b =>
                {
                    b.HasOne("NhaMapThep.Domain.Entities.ConfigTable.LoaiCongTacEntity", "LoaiCongTac")
                        .WithMany()
                        .HasForeignKey("LoaiCongTacID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NhaMapThep.Domain.Entities.NhanVienEntity", "NhanVien")
                        .WithMany()
                        .HasForeignKey("MaSoNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiCongTac");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("NhaMapThep.Domain.Entities.LichSuNghiPhepNhanVienEntity", b =>
                {
                    b.HasOne("NhaMapThep.Domain.Entities.ConfigTable.LoaiNghiPhepEntity", "LoaiNghiPhep")
                        .WithMany()
                        .HasForeignKey("LoaiNghiPhepID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NhaMapThep.Domain.Entities.NhanVienEntity", "NhanVien")
                        .WithMany()
                        .HasForeignKey("MaSoNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NhaMapThep.Domain.Entities.NhanVienEntity", "NguoiDuyetNhanVien")
                        .WithMany()
                        .HasForeignKey("NguoiDuyet")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("LoaiNghiPhep");

                    b.Navigation("NguoiDuyetNhanVien");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("NhaMapThep.Domain.Entities.LuongThoiGianEntity", b =>
                {
                    b.HasOne("NhaMapThep.Domain.Entities.NhanVienEntity", "NhanVien")
                        .WithMany()
                        .HasForeignKey("MaSoNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("NhaMapThep.Domain.Entities.NhanVienEntity", b =>
                {
                    b.HasOne("NhaMapThep.Domain.Entities.ConfigTable.ThongTinChucVuEntity", "ChucVu")
                        .WithMany()
                        .HasForeignKey("ChucVuID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NhaMapThep.Domain.Entities.ConfigTable.TinhTrangLamViecEntity", "TinhTrangLamViec")
                        .WithMany()
                        .HasForeignKey("TinhTrangLamViecID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChucVu");

                    b.Navigation("TinhTrangLamViec");
                });

            modelBuilder.Entity("NhaMapThep.Domain.Entities.PhuCapNhanVienEntity", b =>
                {
                    b.HasOne("NhaMapThep.Domain.Entities.NhanVienEntity", "NhanVien")
                        .WithMany()
                        .HasForeignKey("MaSoNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("NhaMapThep.Domain.Entities.QuaTrinhNhanSuEntity", b =>
                {
                    b.HasOne("NhaMapThep.Domain.Entities.ConfigTable.ThongTinChucDanhEntity", "ChucDanh")
                        .WithMany()
                        .HasForeignKey("ChucDanhID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NhaMapThep.Domain.Entities.ConfigTable.ThongTinChucVuEntity", "ChucVu")
                        .WithMany()
                        .HasForeignKey("ChucVuID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NhaMapThep.Domain.Entities.ConfigTable.ThongTinQuaTrinhNhanSuEntity", "LoaiQuaTrinh")
                        .WithMany()
                        .HasForeignKey("LoaiQuaTrinhID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NhaMapThep.Domain.Entities.NhanVienEntity", "NhanVien")
                        .WithMany()
                        .HasForeignKey("MaSoNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NhaMapThep.Domain.Entities.ConfigTable.PhongBanEntity", "PhongBan")
                        .WithMany()
                        .HasForeignKey("PhongBanID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChucDanh");

                    b.Navigation("ChucVu");

                    b.Navigation("LoaiQuaTrinh");

                    b.Navigation("NhanVien");

                    b.Navigation("PhongBan");
                });

            modelBuilder.Entity("NhaMapThep.Domain.Entities.ThongTinDangVienEntity", b =>
                {
                    b.HasOne("NhaMapThep.Domain.Entities.ConfigTable.DonViCongTacEntity", "DonViCongTac")
                        .WithMany()
                        .HasForeignKey("DonViCongTacID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NhaMapThep.Domain.Entities.NhanVienEntity", "NhanVien")
                        .WithMany()
                        .HasForeignKey("NhanVienID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonViCongTac");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("NhaMapThep.Domain.Entities.ThongTinDaoTaoEntity", b =>
                {
                    b.HasOne("NhaMapThep.Domain.Entities.ConfigTable.TrinhDoHocVanEntity", "TrinhDoHocVan")
                        .WithMany()
                        .HasForeignKey("MaTrinhDoHocVanID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NhaMapThep.Domain.Entities.NhanVienEntity", "NhanVien")
                        .WithMany()
                        .HasForeignKey("NhanVienID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");

                    b.Navigation("TrinhDoHocVan");
                });

            modelBuilder.Entity("NhaMapThep.Domain.Entities.ThongTinGiamTruGiaCanhEntity", b =>
                {
                    b.HasOne("NhaMapThep.Domain.Entities.ConfigTable.ThongTinGiamTruEntity", "ThongTinGiamTru")
                        .WithMany()
                        .HasForeignKey("MaGiamTruID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NhaMapThep.Domain.Entities.NhanVienEntity", "NhanVien")
                        .WithMany()
                        .HasForeignKey("NhanVienID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");

                    b.Navigation("ThongTinGiamTru");
                });

            modelBuilder.Entity("NhaMapThep.Domain.Entities.ThongTinLuongNhanVienEntity", b =>
                {
                    b.HasOne("NhaMapThep.Domain.Entities.HopDongEntity", "HopDong")
                        .WithMany()
                        .HasForeignKey("MaSoHopDong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NhaMapThep.Domain.Entities.NhanVienEntity", "NhanVien")
                        .WithMany()
                        .HasForeignKey("MaSoNhanVien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NhaMapThep.Domain.Entities.NhanVienEntity", null)
                        .WithMany("ThongTinLuongNhanViens")
                        .HasForeignKey("NhanVienEntityID");

                    b.Navigation("HopDong");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("NhaMayThep.Infrastructure.Persistence.ThongTinCongDoanEntity", b =>
                {
                    b.HasOne("NhaMapThep.Domain.Entities.NhanVienEntity", "NhanVien")
                        .WithMany()
                        .HasForeignKey("NhanVienID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("NhaMapThep.Domain.Entities.BaoHiemNhanVienEntity", b =>
                {
                    b.Navigation("BaoHiems");
                });

            modelBuilder.Entity("NhaMapThep.Domain.Entities.NhanVienEntity", b =>
                {
                    b.Navigation("HopDongs");

                    b.Navigation("ThongTinLuongNhanViens");
                });

            modelBuilder.Entity("NhaMapThep.Domain.Entities.PhuCapNhanVienEntity", b =>
                {
                    b.Navigation("PhuCaps");
                });
#pragma warning restore 612, 618
        }
    }
}
