// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NhaMayThep.Infrastructure.Persistence;

#nullable disable

namespace NhaMayThep.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NhaMapThep.Domain.Entities.CanCuocCongDanEntity", b =>
                {
                    b.Property<string>("CanCuocCongDan")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("DanToc")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("DiaChiThuongTru")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("GioiTinh")
                        .HasColumnType("bit");

                    b.Property<string>("HoVaTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayCap")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayCapNhatCuoi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhatID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTaoID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoiCap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QueQuan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuocTich")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TonGiao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CanCuocCongDan");

                    b.ToTable("CanCuocCongDan");
                });

            modelBuilder.Entity("NhaMapThep.Domain.Entities.ChiTietDangVienEntity", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ChucVuDang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DangVienID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("DonViCongTacID")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayCapNhatCuoi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhatID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTaoID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrinhDoChinhTri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("DangVienID");

                    b.HasIndex("DonViCongTacID");

                    b.ToTable("ChiTietDangVien");
                });

            modelBuilder.Entity("NhaMapThep.Domain.Entities.ConfigTable.CapBacLuongEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<float>("HeSoLuong")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("CapBacLuong");
                });

            modelBuilder.Entity("NhaMapThep.Domain.Entities.ConfigTable.DonViCongTacEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("DonViCongTac");
                });

            modelBuilder.Entity("NhaMapThep.Domain.Entities.ConfigTable.LoaiHopDongEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TenHopDong");

                    b.HasKey("ID")
                        .HasName("MaHopDong");

                    b.ToTable("LoaiHopDong");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "HopDongThuViec"
                        },
                        new
                        {
                            ID = 2,
                            Name = "HopDongCoThoiHan"
                        },
                        new
                        {
                            ID = 3,
                            Name = "HopDongKhongThoiHan"
                        });
                });

            modelBuilder.Entity("NhaMapThep.Domain.Entities.ConfigTable.ThongTinChucDanhEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TenChucDanh");

                    b.HasKey("ID")
                        .HasName("MaChucDanh");

                    b.ToTable("ThongTinChucDanh");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "GiamDoc"
                        },
                        new
                        {
                            ID = 2,
                            Name = "PhoGiamDoc"
                        },
                        new
                        {
                            ID = 3,
                            Name = "TruongPhong"
                        },
                        new
                        {
                            ID = 4,
                            Name = "PhoPhong"
                        },
                        new
                        {
                            ID = 5,
                            Name = "NhanVien"
                        });
                });

            modelBuilder.Entity("NhaMapThep.Domain.Entities.ConfigTable.ThongTinChucVuEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TenChucVu");

                    b.HasKey("ID")
                        .HasName("MaChucVu");

                    b.ToTable("ThongTinChucVu");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            ID = 2,
                            Name = "Truong Phong Nhan Su"
                        },
                        new
                        {
                            ID = 3,
                            Name = "Quan Li"
                        },
                        new
                        {
                            ID = 4,
                            Name = "Nhan Vien"
                        });
                });

            modelBuilder.Entity("NhaMapThep.Domain.Entities.ConfigTable.ThongTinGiamTruEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TenMaGiamTru");

                    b.Property<decimal>("SoTienGiamTru")
                        .HasColumnType("decimal(18, 4)");

                    b.HasKey("ID")
                        .HasName("MaGiamTru");

                    b.ToTable("ThongTinGiamTru");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "GiamTruBanThan",
                            SoTienGiamTru = 11000000m
                        },
                        new
                        {
                            ID = 2,
                            Name = "GiamTruNguoiPhuThuoc",
                            SoTienGiamTru = 4400000m
                        });
                });

            modelBuilder.Entity("NhaMapThep.Domain.Entities.ConfigTable.ThongTinPhuCapEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SoTienPhuCap")
                        .HasColumnType("decimal(18, 4)");

                    b.HasKey("ID");

                    b.ToTable("ThongTinPhuCap");
                });

            modelBuilder.Entity("NhaMapThep.Domain.Entities.ConfigTable.TinhTrangLamViecEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TenMaTinhTrangLamViec");

                    b.HasKey("ID")
                        .HasName("MaTinhTrangLamViecID");

                    b.ToTable("ThongTinTinhTrangLamViec");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "DangLamViec"
                        },
                        new
                        {
                            ID = 2,
                            Name = "DaNghiViec"
                        },
                        new
                        {
                            ID = 3,
                            Name = "DangThuViec"
                        },
                        new
                        {
                            ID = 4,
                            Name = "DangNghiPhep"
                        });
                });

            modelBuilder.Entity("NhaMapThep.Domain.Entities.ConfigTable.TrinhDoHocVanEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TenTrinhDo");

                    b.HasKey("ID")
                        .HasName("MaTrinhDoHocVan");

                    b.ToTable("TrinhDoHocVan");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Tien Si"
                        },
                        new
                        {
                            ID = 2,
                            Name = "Thac Si"
                        },
                        new
                        {
                            ID = 3,
                            Name = "Dai Hoc"
                        },
                        new
                        {
                            ID = 4,
                            Name = "Cao Dang"
                        },
                        new
                        {
                            ID = 5,
                            Name = "Trung Cap"
                        });
                });

            modelBuilder.Entity("NhaMapThep.Domain.Entities.HopDongEntity", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BoPhanLamViec")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ChucDanhID")
                        .HasColumnType("int");

                    b.Property<int>("ChucVuID")
                        .HasColumnType("int");

                    b.Property<string>("DiaDiemLamViec")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HeSoLuongID")
                        .HasColumnType("int");

                    b.Property<int>("LoaiHopDongID")
                        .HasColumnType("int");

                    b.Property<decimal>("LuongCoBan")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("NgayCapNhatCuoi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKy")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhatID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTaoID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NhanVienID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PhuCapID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ThoiHanHopDong")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ChucDanhID");

                    b.HasIndex("ChucVuID");

                    b.HasIndex("HeSoLuongID");

                    b.HasIndex("LoaiHopDongID");

                    b.HasIndex("NhanVienID");

                    b.ToTable("HopDong");
                });

            modelBuilder.Entity("NhaMapThep.Domain.Entities.Mapping.NhanVienMapThongTinCanCuocCongDan", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("CanCuocCongDan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaSoNhanVien")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NhanVienEntityID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ThongTinGiamTruGiaCanhNavigationCanCuocCongDan")
                        .HasColumnType("nvarchar(12)");

                    b.HasKey("ID");

                    b.HasIndex("MaSoNhanVien");

                    b.HasIndex("NhanVienEntityID");

                    b.HasIndex("ThongTinGiamTruGiaCanhNavigationCanCuocCongDan")
                        .IsUnique()
                        .HasFilter("[ThongTinGiamTruGiaCanhNavigationCanCuocCongDan] IS NOT NULL");

                    b.ToTable("nhanVienMapThongTinCanCuocCongDans");
                });

            modelBuilder.Entity("NhaMapThep.Domain.Entities.NhanVienEntity", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CanCuocCongDan")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<int>("ChucVuID")
                        .HasColumnType("int");

                    b.Property<string>("DiaChiLienLac")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoVaTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaSoThue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayCapNhatCuoi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayVaoCongTy")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhatID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTaoID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDienThoaiLienLac")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<int?>("SoNguoiPhuThuoc")
                        .HasColumnType("int");

                    b.Property<string>("SoTaiKhoan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenNganHang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TinhTrangLamViecID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ChucVuID");

                    b.HasIndex("TinhTrangLamViecID");

                    b.ToTable("NhanVien");
                });

            modelBuilder.Entity("NhaMapThep.Domain.Entities.ThongTinDangVienEntity", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CapDangVien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayCapNhatCuoi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayVaoDang")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhatID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTaoID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NhanVienID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex("NhanVienID");

                    b.ToTable("ThongTinDangVien");
                });

            modelBuilder.Entity("NhaMapThep.Domain.Entities.ThongTinDaoTaoEntity", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ChuyenNganh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaTrinhDoHocVanID")
                        .HasColumnType("int");

                    b.Property<DateTime>("NamTotNghiep")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayCapNhatCuoi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhatID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTaoID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NhanVienID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenTruong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrinhDoVanHoa")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("MaTrinhDoHocVanID");

                    b.HasIndex("NhanVienID");

                    b.ToTable("ThongTinDaoTao");
                });

            modelBuilder.Entity("NhaMapThep.Domain.Entities.ThongTinGiamTruGiaCanhEntity", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CanCuocCongDan")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("DiaChiLienLac")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaGiamTruID")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayCapNhatCuoi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayXacNhanPhuThuoc")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhatID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTaoID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NhanVienID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("QuanHeVoiNhanVien")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("mapID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("MaGiamTruID");

                    b.HasIndex("NhanVienID");

                    b.HasIndex("mapID");

                    b.ToTable("ThongTinGiamTruGiaCanh");
                });

            modelBuilder.Entity("NhaMayThep.Infrastructure.Persistence.ThongTinCongDoanEntity", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgayCapNhatCuoi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayGiaNhap")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhatID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTaoID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NhanVienID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("ThuKiCongDoan")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.HasIndex("NhanVienID");

                    b.ToTable("ThongTinCongDoan");
                });

            modelBuilder.Entity("NhaMapThep.Domain.Entities.ChiTietDangVienEntity", b =>
                {
                    b.HasOne("NhaMapThep.Domain.Entities.ThongTinDangVienEntity", "ThongTinDangVien")
                        .WithMany()
                        .HasForeignKey("DangVienID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NhaMapThep.Domain.Entities.ConfigTable.DonViCongTacEntity", "DonViCongTac")
                        .WithMany()
                        .HasForeignKey("DonViCongTacID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonViCongTac");

                    b.Navigation("ThongTinDangVien");
                });

            modelBuilder.Entity("NhaMapThep.Domain.Entities.HopDongEntity", b =>
                {
                    b.HasOne("NhaMapThep.Domain.Entities.ConfigTable.ThongTinChucDanhEntity", "ChucDanh")
                        .WithMany()
                        .HasForeignKey("ChucDanhID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NhaMapThep.Domain.Entities.ConfigTable.ThongTinChucVuEntity", "ChucVu")
                        .WithMany()
                        .HasForeignKey("ChucVuID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NhaMapThep.Domain.Entities.ConfigTable.CapBacLuongEntity", "CapBacLuong")
                        .WithMany()
                        .HasForeignKey("HeSoLuongID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NhaMapThep.Domain.Entities.ConfigTable.LoaiHopDongEntity", "LoaiHopDong")
                        .WithMany()
                        .HasForeignKey("LoaiHopDongID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NhaMapThep.Domain.Entities.NhanVienEntity", "NhanVien")
                        .WithMany()
                        .HasForeignKey("NhanVienID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CapBacLuong");

                    b.Navigation("ChucDanh");

                    b.Navigation("ChucVu");

                    b.Navigation("LoaiHopDong");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("NhaMapThep.Domain.Entities.Mapping.NhanVienMapThongTinCanCuocCongDan", b =>
                {
                    b.HasOne("NhaMapThep.Domain.Entities.NhanVienEntity", "NhanVienNavigation")
                        .WithMany()
                        .HasForeignKey("MaSoNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NhaMapThep.Domain.Entities.NhanVienEntity", null)
                        .WithMany("NhanVienMappings")
                        .HasForeignKey("NhanVienEntityID");

                    b.HasOne("NhaMapThep.Domain.Entities.ThongTinGiamTruGiaCanhEntity", "ThongTinGiamTruGiaCanhNavigation")
                        .WithOne()
                        .HasForeignKey("NhaMapThep.Domain.Entities.Mapping.NhanVienMapThongTinCanCuocCongDan", "ThongTinGiamTruGiaCanhNavigationCanCuocCongDan")
                        .HasPrincipalKey("NhaMapThep.Domain.Entities.ThongTinGiamTruGiaCanhEntity", "CanCuocCongDan");

                    b.Navigation("NhanVienNavigation");

                    b.Navigation("ThongTinGiamTruGiaCanhNavigation");
                });

            modelBuilder.Entity("NhaMapThep.Domain.Entities.NhanVienEntity", b =>
                {
                    b.HasOne("NhaMapThep.Domain.Entities.ConfigTable.ThongTinChucVuEntity", "ChucVu")
                        .WithMany()
                        .HasForeignKey("ChucVuID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NhaMapThep.Domain.Entities.ConfigTable.TinhTrangLamViecEntity", "TinhTrangLamViec")
                        .WithMany()
                        .HasForeignKey("TinhTrangLamViecID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChucVu");

                    b.Navigation("TinhTrangLamViec");
                });

            modelBuilder.Entity("NhaMapThep.Domain.Entities.ThongTinDangVienEntity", b =>
                {
                    b.HasOne("NhaMapThep.Domain.Entities.NhanVienEntity", "NhanVien")
                        .WithMany()
                        .HasForeignKey("NhanVienID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("NhaMapThep.Domain.Entities.ThongTinDaoTaoEntity", b =>
                {
                    b.HasOne("NhaMapThep.Domain.Entities.ConfigTable.TrinhDoHocVanEntity", "TrinhDoHocVan")
                        .WithMany()
                        .HasForeignKey("MaTrinhDoHocVanID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NhaMapThep.Domain.Entities.NhanVienEntity", "NhanVien")
                        .WithMany()
                        .HasForeignKey("NhanVienID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");

                    b.Navigation("TrinhDoHocVan");
                });

            modelBuilder.Entity("NhaMapThep.Domain.Entities.ThongTinGiamTruGiaCanhEntity", b =>
                {
                    b.HasOne("NhaMapThep.Domain.Entities.CanCuocCongDanEntity", "SoCanCuoc")
                        .WithOne("ThongTinGiamTruGiaCanh")
                        .HasForeignKey("NhaMapThep.Domain.Entities.ThongTinGiamTruGiaCanhEntity", "CanCuocCongDan")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NhaMapThep.Domain.Entities.ConfigTable.ThongTinGiamTruEntity", "ThongTinGiamTru")
                        .WithMany()
                        .HasForeignKey("MaGiamTruID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NhaMapThep.Domain.Entities.NhanVienEntity", "NhanVien")
                        .WithMany()
                        .HasForeignKey("NhanVienID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NhaMapThep.Domain.Entities.Mapping.NhanVienMapThongTinCanCuocCongDan", "map")
                        .WithMany()
                        .HasForeignKey("mapID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");

                    b.Navigation("SoCanCuoc");

                    b.Navigation("ThongTinGiamTru");

                    b.Navigation("map");
                });

            modelBuilder.Entity("NhaMayThep.Infrastructure.Persistence.ThongTinCongDoanEntity", b =>
                {
                    b.HasOne("NhaMapThep.Domain.Entities.NhanVienEntity", "NhanVien")
                        .WithMany()
                        .HasForeignKey("NhanVienID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("NhaMapThep.Domain.Entities.CanCuocCongDanEntity", b =>
                {
                    b.Navigation("ThongTinGiamTruGiaCanh");
                });

            modelBuilder.Entity("NhaMapThep.Domain.Entities.NhanVienEntity", b =>
                {
                    b.Navigation("NhanVienMappings");
                });
#pragma warning restore 612, 618
        }
    }
}
